artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/jayasooryantm/weather-data/raw/main/data_bundle.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/data
  dataset_file: artifacts/data_validation/weather_data.csv
  STATUS_FILE: artifacts/data_validation/status.txt

