artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/jayasooryantm/weather-data/raw/main/data_bundle.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/data

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/data
  dataset_file: artifacts/data_validation/weather_data.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  STATUS_FILE: artifacts/data_validation/status.txt
  dataset_file: artifacts/data_validation/weather_data.csv
  transformed_data_filepath: artifacts/data_transformation/weather_data.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/weather_data.csv
  test_data_path: artifacts/data_transformation/weather_data_test.csv
  model_path: artifacts/model_trainer/models/model.pth

model_eval:
  root_dir: artifacts/model_evaluation
  model_path: artifacts/model_trainer/models/model.pth
  test_data_path: artifacts/model_evaluation/weather_data_test.csv
  mlflow_uri: https://dagshub.com/jayasooryan.tm/weather-prediction.mlflow
  mlflow_user: jayasooryan.tm
  mlflow_key: 4cf05aa75bfc9ab0b4f4ac28b1ad79fdd287fd24